[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    #https://github.com/Makerfabs/Makerfabs-ESP32-UWB-DW3000.git
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO

board_microros_distro = humble     # change to iron / jazzy / rolling if you use a different ROS 2 distro
board_microros_transport = wifi

build_flags = 
    -D RMW_UXRCE_TRANSPORT_UDP
    -D MAX_IP_LEN=16
    -D UXRCE_TRANSPORT_UDP_IP=UDP_IPV4
; ================== ANCHOR (Responder) ==================
[env:anchor]
extends = env:esp32dev
build_src_filter = +<range_anchor.cpp> -<main.cpp> -<range_tag.cpp>

; ================== TAG (Initiator) ==================
[env:tag]
extends = env:esp32dev
build_src_filter = +<range_tag.cpp> -<main.cpp> -<range_anchor.cpp>
lib_archive = false

[env:tag_IMU]
extends = env:esp32dev
build_src_filter = +<range_tag_IMU.cpp> -<main.cpp> -<range_anchor.cpp> -<range_tag.cpp>
lib_archive = false